package main

import (
	"fmt"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

const version = "0.1.0"

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, f := range plugin.Files {
			if !f.Generate {
				continue
			}
			if len(f.Services) == 0 {
				continue
			}
			if err := generateFile(plugin, f); err != nil {
				return err
			}
		}
		return nil
	})
}

var (
	ginPkg       = protogen.GoImportPath("github.com/gin-gonic/gin")
	httpPkg      = protogen.GoImportPath("net/http")
	errorsPkg    = protogen.GoImportPath("errors")
	jsonPkg      = protogen.GoImportPath("encoding/json")
	ioPkg        = protogen.GoImportPath("io")
	protojsonPkg = protogen.GoImportPath("google.golang.org/protobuf/encoding/protojson")
)

func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	filename := file.GeneratedFilenamePrefix + "_gin_http.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-gin-http. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-gin-http v", version)
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, service := range file.Services {
		if err := genService(g, file, service); err != nil {
			return err
		}
	}

	return nil
}

type methodHTTP struct {
	method *protogen.Method
	verb   string
	path   string
}

func genService(g *protogen.GeneratedFile, file *protogen.File, service *protogen.Service) error {
	var methods []methodHTTP
	for _, m := range service.Methods {
		if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
			continue
		}
		rule := getHTTPRule(m)
		if rule == nil {
			continue
		}
		verb, path := extractVerbPath(rule)
		if verb == "" {
			continue
		}
		methods = append(methods, methodHTTP{m, verb, path})
	}

	if len(methods) == 0 {
		return nil
	}

	serverName := service.GoName + "HTTPServer"

	for _, m := range methods {
		constName := fmt.Sprintf("Operation%s%s", service.GoName, m.method.GoName)
		g.P("const ", constName, ` = "/`, string(file.Desc.Package()), ".", service.Desc.Name(), "/", m.method.Desc.Name(), `"`)
	}
	g.P()

	g.P("type ", serverName, " interface {")
	for _, m := range methods {
		g.P("\t", m.method.GoName, "(*", ginPkg.Ident("Context"), ", *", m.method.Input.GoIdent, ") (*", m.method.Output.GoIdent, ", error)")
	}
	g.P("}")
	g.P()

	g.P("func Register", serverName, "(router *", ginPkg.Ident("RouterGroup"), ", srv ", serverName, ") {")
	for _, m := range methods {
		handlerName := fmt.Sprintf("_%s_%s0_HTTP_Handler", service.GoName, m.method.GoName)
		g.P("\trouter.", strings.ToUpper(m.verb), `("`, m.path, `", `, handlerName, "(srv))")
	}
	g.P("}")
	g.P()

	for _, m := range methods {
		genHandler(g, file, service, m.method, m.verb)
	}

	return nil
}

func genHandler(g *protogen.GeneratedFile, file *protogen.File, service *protogen.Service, method *protogen.Method, verb string) {
	handlerName := fmt.Sprintf("_%s_%s0_HTTP_Handler", service.GoName, method.GoName)
	serverName := service.GoName + "HTTPServer"

	g.P("func ", handlerName, "(srv ", serverName, ") ", ginPkg.Ident("HandlerFunc"), " {")
	g.P("\treturn func(c *", ginPkg.Ident("Context"), ") {")
	g.P("\t\tvar in ", method.Input.GoIdent)

	upperVerb := strings.ToUpper(verb)
	if upperVerb == "GET" || upperVerb == "DELETE" {
		genQueryBinding(g)
	} else {
		genBodyBinding(g)
	}

	g.P("\t\tout, err := srv.", method.GoName, "(c, &in)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\thttpCode := ", httpPkg.Ident("StatusInternalServerError"))
	g.P("\t\t\tbizCode := 500")
	g.P("\t\t\tmsg := err.Error()")
	g.P("\t\t\tvar coder interface{ HTTPCode() int; BizCode() int; Error() string }")
	g.P("\t\t\tif ", errorsPkg.Ident("As"), "(err, &coder) {")
	g.P("\t\t\t\thttpCode = coder.HTTPCode()")
	g.P("\t\t\t\tbizCode = coder.BizCode()")
	g.P("\t\t\t\tmsg = coder.Error()")
	g.P("\t\t\t}")
	g.P("\t\t\tc.JSON(httpCode, ", ginPkg.Ident("H"), `{"code": bizCode, "message": msg})`)
	g.P("\t\t\treturn")
	g.P("\t\t}")
	g.P("\t\tdataBytes, err := (", protojsonPkg.Ident("MarshalOptions"), "{EmitUnpopulated: true, UseProtoNames: true}).Marshal(out)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\tc.JSON(", httpPkg.Ident("StatusInternalServerError"), ", ", ginPkg.Ident("H"), `{"code": 500, "message": err.Error()})`)
	g.P("\t\t\treturn")
	g.P("\t\t}")
	g.P("\t\tc.JSON(", httpPkg.Ident("StatusOK"), ", ", ginPkg.Ident("H"), `{"code": 0, "message": "ok", "data": `, jsonPkg.Ident("RawMessage"), `(dataBytes)})`)
	g.P("\t}")
	g.P("}")
	g.P()
}

func genQueryBinding(g *protogen.GeneratedFile) {
	g.P("\t\tquery := c.Request.URL.Query()")
	g.P("\t\tif len(query) > 0 {")
	g.P("\t\t\tqueryMap := make(map[string]interface{})")
	g.P("\t\t\tfor key, values := range query {")
	g.P("\t\t\t\tif len(values) == 1 {")
	g.P("\t\t\t\t\tqueryMap[key] = values[0]")
	g.P("\t\t\t\t} else {")
	g.P("\t\t\t\t\tqueryMap[key] = values")
	g.P("\t\t\t\t}")
	g.P("\t\t\t}")
	g.P("\t\t\tqueryJSON, err := ", jsonPkg.Ident("Marshal"), "(queryMap)")
	g.P("\t\t\tif err != nil {")
	g.P("\t\t\t\tc.JSON(", httpPkg.Ident("StatusBadRequest"), ", ", ginPkg.Ident("H"), `{"code": 400, "message": "invalid query parameters"})`)
	g.P("\t\t\t\treturn")
	g.P("\t\t\t}")
	g.P("\t\t\tif err := (", protojsonPkg.Ident("UnmarshalOptions"), "{DiscardUnknown: true}).Unmarshal(queryJSON, &in); err != nil {")
	g.P("\t\t\t\tc.JSON(", httpPkg.Ident("StatusBadRequest"), ", ", ginPkg.Ident("H"), `{"code": 400, "message": err.Error()})`)
	g.P("\t\t\t\treturn")
	g.P("\t\t\t}")
	g.P("\t\t}")
}

func genBodyBinding(g *protogen.GeneratedFile) {
	g.P("\t\tdata, err := ", ioPkg.Ident("ReadAll"), "(c.Request.Body)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\tc.JSON(", httpPkg.Ident("StatusBadRequest"), ", ", ginPkg.Ident("H"), `{"code": 400, "message": "failed to read request body"})`)
	g.P("\t\t\treturn")
	g.P("\t\t}")
	g.P("\t\tif len(data) > 0 {")
	g.P("\t\t\tif err := (", protojsonPkg.Ident("UnmarshalOptions"), "{DiscardUnknown: true}).Unmarshal(data, &in); err != nil {")
	g.P("\t\t\t\tc.JSON(", httpPkg.Ident("StatusBadRequest"), ", ", ginPkg.Ident("H"), `{"code": 400, "message": err.Error()})`)
	g.P("\t\t\t\treturn")
	g.P("\t\t\t}")
	g.P("\t\t}")
}

func getHTTPRule(method *protogen.Method) *annotations.HttpRule {
	options := method.Desc.Options()
	if options == nil {
		return nil
	}
	if !proto.HasExtension(options, annotations.E_Http) {
		return nil
	}
	ext := proto.GetExtension(options, annotations.E_Http)
	rule, ok := ext.(*annotations.HttpRule)
	if !ok {
		return nil
	}
	return rule
}

func extractVerbPath(rule *annotations.HttpRule) (string, string) {
	switch pattern := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return "GET", pattern.Get
	case *annotations.HttpRule_Post:
		return "POST", pattern.Post
	case *annotations.HttpRule_Put:
		return "PUT", pattern.Put
	case *annotations.HttpRule_Delete:
		return "DELETE", pattern.Delete
	case *annotations.HttpRule_Patch:
		return "PATCH", pattern.Patch
	}
	return "", ""
}
