// Code generated by protoc-gen-gin-http. DO NOT EDIT.
// versions:
// - protoc-gen-gin-http v0.1.0
// source: example/api/greeter/greeter.proto

package greeter

import (
	json "encoding/json"
	gin "github.com/gin-gonic/gin"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	http "net/http"
)

const OperationGreeterSayHello = "/greeter.Greeter/SayHello"
const OperationGreeterCreateUser = "/greeter.Greeter/CreateUser"
const OperationGreeterGetUser = "/greeter.Greeter/GetUser"

type GreeterHTTPServer interface {
	SayHello(*gin.Context, *HelloRequest) (*HelloReply, error)
	CreateUser(*gin.Context, *CreateUserRequest) (*CreateUserReply, error)
	GetUser(*gin.Context, *GetUserRequest) (*GetUserReply, error)
}

func RegisterGreeterHTTPServer(router *gin.RouterGroup, srv GreeterHTTPServer) {
	router.GET("/api/v1/greeter/hello", _Greeter_SayHello0_HTTP_Handler(srv))
	router.POST("/api/v1/greeter/user", _Greeter_CreateUser0_HTTP_Handler(srv))
	router.GET("/api/v1/greeter/user", _Greeter_GetUser0_HTTP_Handler(srv))
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in HelloRequest
		query := c.Request.URL.Query()
		if len(query) > 0 {
			queryMap := make(map[string]interface{})
			for key, values := range query {
				if len(values) == 1 {
					queryMap[key] = values[0]
				} else {
					queryMap[key] = values
				}
			}
			queryJSON, err := json.Marshal(queryMap)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"code": 400, "message": "invalid query parameters"})
				return
			}
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(queryJSON, &in); err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"code": 400, "message": err.Error()})
				return
			}
		}
		out, err := srv.SayHello(c, &in)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"code": 500, "message": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"code": 0, "message": "ok", "data": out})
	}
}

func _Greeter_CreateUser0_HTTP_Handler(srv GreeterHTTPServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateUserRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"code": 400, "message": "failed to read request body"})
			return
		}
		if len(data) > 0 {
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(data, &in); err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"code": 400, "message": err.Error()})
				return
			}
		}
		out, err := srv.CreateUser(c, &in)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"code": 500, "message": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"code": 0, "message": "ok", "data": out})
	}
}

func _Greeter_GetUser0_HTTP_Handler(srv GreeterHTTPServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetUserRequest
		query := c.Request.URL.Query()
		if len(query) > 0 {
			queryMap := make(map[string]interface{})
			for key, values := range query {
				if len(values) == 1 {
					queryMap[key] = values[0]
				} else {
					queryMap[key] = values
				}
			}
			queryJSON, err := json.Marshal(queryMap)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"code": 400, "message": "invalid query parameters"})
				return
			}
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(queryJSON, &in); err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"code": 400, "message": err.Error()})
				return
			}
		}
		out, err := srv.GetUser(c, &in)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"code": 500, "message": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"code": 0, "message": "ok", "data": out})
	}
}
